version: '0.2'
language: en
allowCompoundWords: true
caseSensitive: false
ignoreRandomStrings: true
words:
  - arnaud
  - auvred
  - bivariant
  - blueprintjs
  - corsa
  - johnsoncodehk
  - klass
  - noshiro
  - oxlint
  - oxlintrc
  - pikachu
  - rslint
  - rstack
  - sindresorhus
  - testw
  - tscw
  - tses
  - tsgolint
  - tsslint
  - tsutils
  - unshifted
ignorePaths:
  - pnpm-lock.yaml
  - pnpm-workspace.yaml
  - dist/**
  - docs/**
  - agents/common/**
  - test/**
